### ISSUE TITLE
Outdated changelog

### ISSUE THREAD

**Issue by filipkis** [pusher/pusher-http-ruby#146]
Hi there, 

I've noticed that there is a 1.3.3 version but it doesn't appear in the changelog (nor does 1.3.2) and additionally it's not even tagged as a release.

It would be great if changelog would be kept up to date and if releases are tagged so it's easy to review changes before upgrading to new version of the gem.

Thanks

**Comment by filipkis** [comment]
@topliceanu and @vivangkumar I know you're not maintaining this repo anymore, but could you please ensure that new maintainers keep to good practice of updating the changelog and making a proper release instead of just bumping the version in the code.

Thanks

**Comment by rafbm** [comment]
I agree with this. I have the habit of always checking changelogs in GitHub repos based on the `Gemfile.lock` diff after running `bundle update`. In the unfortunate cases where gems don’t maintain a changelog, I resort to compare links like https://github.com/pusher/pusher-http-ruby/compare/v1.3.2...v1.3.3 but can’t even do so now because tag v1.3.3 doesn’t exist.

For others who end up here, I produced the diff between gem versions 1.3.2 and 1.3.3:
https://gist.github.com/rafbm/6a2ecc928132f210ff71fb48db599a90

I guess this update hasn’t been documented because it was mostly a marketing one, pretty much only renaming the “Pusher” product to “Channels”.

**Comment by annzenkina** [comment]
Hey @filipkis @rafbm , thanks for opening an issue! This is true, looks like we forgot to update the Changelog last two minor version changes. I'll fix that in the nearest future and let you know once it's done.
